### ISSUE TITLE
How to use native MD editor in a cell

### ISSUE THREAD

**Issue by Soltus** [genepattern/jupyter-wysiwyg#12]
I need to paste a large section of MD 
I tried to paste it into the source code, but it didn't work

**Comment by tmtabor** [comment]
Unfortunately the TinyMCE editor used by jupyter-wysiwyg doesn't know how to parse markdown in the same way as Jupyterlab's custom hybrid HTML/markdown editor. This is something we're looking to improve.

In the meantime, your best best is to paste the markdown into a code cell and then change the cell type to markdown. This will allow the markdown to render, bypassing jupyter-wysiwyg entirely.

**Comment by Soltus** [comment]
Change the cell type to markdown still use jupyter-wysiwyg 😥

**Comment by tmtabor** [comment]
Once you do that, just click the "render" button on the left and it should render the markdown.

**Comment by Soltus** [comment]
i do it 🎉
