### ISSUE TITLE
Enable this plugin on jupyter lab

### ISSUE THREAD

**Issue by raonyguimaraes** [genepattern/jupyter-wysiwyg#3]
Hi there,

Is there a way to make this plugin work with jupyter lab ?

I tried the following without much success:

jupyter serverextension enable --py jupyter_wysiwyg --sys-prefix

https://github.com/jupyterlab/jupyterlab/issues/2349

**Comment by tmtabor** [comment]
Unfortunately, I haven't added Jupyter Lab compatibility to the extension yet. 

Last I checked, the Jupyter Lab extension API was still in flux, so I haven't made too much of an effort to port things over at this early stage. I do plan to add compatibility with Jupyter Lab in the future, once the extension API for it becomes more stable. 

That said, I've been keeping an eye on Jupyter Lab and it looks really promising! I'll make a point to take a look at the API again in the next couple weeks.

**Comment by pdeitel** [comment]
Any updates on this for JupyterLab?

**Comment by tmtabor** [comment]
Short Answer: I'm sorry to say there isn't yet.

Long Answer: While I've spent some time apprising myself of the new front-end stack in JupyterLab (learning PhosphorJS and the new build pipeline), I haven't gotten to the point yet where I've updated my existing nbextensions to labextensions.

**Comment by pdeitel** [comment]
Thanks for the fast response!


On Nov 9, 2017, at 3:12 PM, Thorin Tabor <notifications@github.com> wrote:

Short Answer: I'm sorry to say there isn't yet.

Long Answer: While I've spent some time apprising myself of the new front-end stack in JupyterLab (learning PhosphorJS and the new build pipeline), I haven't gotten to the point yet where I've updated my existing nbextensions to labextensions.

**Comment by raonyguimaraes** [comment]
Hi pdeitel,

Can you explain what work would be involved on converting this from nbextensions to labextensions?

I'm very keen to get this plugin into jupyerlab.

**Comment by pdeitel** [comment]
@raonyguimaraes I am not a Jupyter developer, so I don't know the requirements of either nbextensions or labextensions. Sorry! I am simply a Jupyter user interested in WYSIWYG editing capabilities.

**Comment by BobCashStory** [comment]
Same interest here, any news in 2020 ?

**Comment by tmtabor** [comment]
As far as JupyterLab goes, the good news is that I've been getting over the learning curve developing extensions for it. In fact, two of the other extensions I develop, [nbtools](https://github.com/genepattern/nbtools/tree/lab) and genepattern-notebook are in alpha on JupyterLab and getting ready to move to a beta release soon. Once they're in beta, jupyter-wysiwg is next.

The bad news is that JupyterLab extensions work completely differently than Jupyter Notebook extensions. Entirely different frontend tech stack (jquery vs. lumino), different language (TypeScript vs. Javascript), different package types (AMD vs. CommonJS) and a completely different API. This is one reason it's taking so long to port. 

Anyway, the short of it is that the extension has to be almost completely rewritten from scratch to work with JupyterLab. A port to lab *will* happen, but a non-alpha release of it is still several months out.

**Comment by BobCashStory** [comment]
Thanks for the answer ! We can wait, or try to help if you want

Le mer. 7 oct. 2020 à 17:51, Thorin Tabor <notifications@github.com> a
écrit :

**Comment by tmtabor** [comment]
JupyterLab support has been functional, albeit in beta for about a year now. It was just merged into the default branch.
